plugins {
  id 'application'
  id 'com.diffplug.spotless' version '6.25.0'
}

repositories {
  mavenCentral()
}

sourceSets {
  main {
    java {
      srcDirs = ['src']
    }
  }
}

application {
  mainClass = project.property('mainClass')
}

dependencies {
  // Add dependencies here, e.g.:
  // implementation 'com.google.guava:guava:33.0.0-jre'
}

spotless {
  java {
    target 'src/**/*.java'
    googleJavaFormat()
  }
}